# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

favicon_mstilecolor = "#603cba"

### BGN: Structured Data ###
  description = "Faithful Athlete by ᜌᜓᜃᜒ (Yuki ・ 雪亮) / Yahuhanan Yukiya Sese Cuneta."
  keywords = ["Faithful Athlete", "Faithful Atleta", "忠実なアスリート", "충실한 운동선수", "충실한 운동 선수", "YourOnlyOne", "YourOnly.One", "Yahuhanan Yukiya Sese Cuneta", "Yuki", "YoHan", "Yo-Han",  "יהוחנן", "ᜌᜓᜃᜒ", "사요한", "謝雪矢（ゆきや）", "스노", "Seu-No", "SeuNo", "Snow", "Yohanan", "ᜌᜓᜑᜈᜈ᜔", "ᜌᜓᜑᜈᜈ᜕", "ᜌᜑᜓᜑᜈᜈ᜔", "ᜌᜑᜓᜑᜈᜈ᜕"] # Can be overriden per page
  images = ["https://rsc.youronly.one/img/y/Faithful_Athlete-logo-02-1500x.webp"]
### END: Structured Data ###

### BGN: Theme Settings ###
  message = ""
  hideAutoMenu = false

  # Pagination options
  paginate = 12
  multipage = false

  # Dark mode
  darkMode = true
### END: Theme Settings ###

### BGN: Other Settings ###
  [semweb]
    datecreated = "2021-02-06"
    sameas = [
      "https://www.facebook.com/faithfulathlete",
      "https://c.im/@YourOnlyOne",
      "https://pixelfed.social/YourOnlyOne",
      "https://www.youtube.com/@YourOnlyOneOfcl",
      "https://www.facebook.com/YourOnly.ONE.ofcl"
    ]
### END: Other Settings ###
